import { Lato, Open_Sans, Philosopher } from 'next/font/google';
import Script from 'next/script';
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

const lato = Lato({
  subsets: ['latin'],
  display: 'swap',
  variable: '--lato',
  weight: ['100', '300', '400', '700', '900']
});
const open_sans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--open-sans',
  weight: ['300', '400', '500', '600', '700', '800']
});
const philosopher = Philosopher({
  subsets: ['latin'],
  display: 'swap',
  variable: '--philosopher',
  weight: ['400', '700']
})

export const metadata = {
  title: "Nagadhat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lato.variable} ${open_sans.variable} ${philosopher.variable}`}>
      <link rel="stylesheet" href="/css/bootstrap.min.css" precedence="default" />
      <link rel="stylesheet" href="/css/slick.css" precedence="default" />
      <link rel="stylesheet" href="/css/slick-theme.css" precedence="default" />
      <link rel="stylesheet" href="/css/brand.css" precedence="default" />
      <link rel="stylesheet" href="/css/category.css" precedence="default" />
      <link rel="stylesheet" href="/css/flash-sale.css" precedence="default" />
      <link rel="stylesheet" href="/css/footer.css" precedence="default" />
      <link rel="stylesheet" href="/css/header.css" precedence="default" />
      <link rel="stylesheet" href="/css/hero-banner.css" precedence="default" />
      <link rel="stylesheet" href="/css/just-for.css" precedence="default" />
      <link rel="stylesheet" href="/css/partner.css" precedence="default" />
      <link rel="stylesheet" href="/css/service.css" precedence="default" />
      <link rel="stylesheet" href="/css/home.css" precedence="default" />
      <link rel="stylesheet" href="/css/login.css" precedence="default" />
      <link rel="stylesheet" href="/css/product-details.css" precedence="default" />
      <link rel="stylesheet" href="/css/product-category.css" precedence="default" />
      <link rel="stylesheet" href="/css/common.css" precedence="default" />
      <link rel="stylesheet" href="/css/responsive.css" precedence="default" />
      {/* <Script strategy="afterInteractive" src="/js/jquery.min.js" /> */}
      <Script strategy="afterInteractive" src="/js/bootstrap.bundle.min.js" />

      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
